// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Grigorii Lapidus

#ifndef CYC_RECORD_H
#define CYC_RECORD_H

#include "RecRule.h"

namespace cyc {

/**
 * @def DECLARE_RECORD_ACCESSORS
 * @brief Macro to declare typed getters and setters for record fields.
 */
#define DECLARE_RECORD_ACCESSORS(NAME, TYPE) \
    TYPE& get##NAME(int id) { return *static_cast<TYPE*>(getVoid(id)); } \
    TYPE* get##NAME##Ptr(int id) { return static_cast<TYPE*>(getVoid(id)); } \
    const TYPE& get##NAME(int id) const { return *static_cast<const TYPE*>(getVoid(id)); } \
    const TYPE* get##NAME##Ptr(int id) const { return static_cast<const TYPE*>(getVoid(id)); } \
    void set##NAME(int id, TYPE val) { *static_cast<TYPE*>(getVoid(id)) = val; }

/**
 * @brief Represents a single record instance.
 *
 * Provides safe access to raw memory based on a RecRule.
 */
class CYCLIB_EXPORT Record {
public:
    /**
     * @brief Constructs a record wrapper.
     * @param r Reference to the rule defining the record structure.
     * @param ptr Pointer to the raw data.
     */
    Record(const RecRule& r, void* ptr);

    /**
     * @brief Checks if the record points to valid data.
     * @return True if valid, false otherwise.
     */
    bool isValid() const;

    /**
     * @brief Updates the underlying data pointer.
     * @param ptr New data pointer.
     */
    void setData(void* ptr);

    /**
     * @brief Clears (zeroes out) the record data.
     */
    void clear();

    /**
     * @brief Copies data from a source memory location.
     * @param src Pointer to source data.
     */
    void copyFrom(const void* src);

    /**
     * @brief Gets a raw pointer to a field by ID.
     * @param id Attribute ID.
     * @return void* pointer to the field data.
     */
    void* getVoid(int id) const;

    // Generic accessors
    double getValue(int id) const;
    void setValue(int id, double val);

    // Typed accessors generated by macro
    DECLARE_RECORD_ACCESSORS(Bool, bool)
    DECLARE_RECORD_ACCESSORS(Char, char)
    DECLARE_RECORD_ACCESSORS(Int8, int8_t)
    DECLARE_RECORD_ACCESSORS(UInt8, uint8_t)
    DECLARE_RECORD_ACCESSORS(Int16, int16_t)
    DECLARE_RECORD_ACCESSORS(UInt16, uint16_t)
    DECLARE_RECORD_ACCESSORS(Int32, int32_t)
    DECLARE_RECORD_ACCESSORS(UInt32, uint32_t)
    DECLARE_RECORD_ACCESSORS(Int64, int64_t)
    DECLARE_RECORD_ACCESSORS(UInt64, uint64_t)
    DECLARE_RECORD_ACCESSORS(Float, float)
    DECLARE_RECORD_ACCESSORS(Double, double)

    // Pointer accessors
    void setPtr(int id, void* val) { *static_cast<void**>(getVoid(id)) = val; }
    void* getPtr(int id) const { return *static_cast<void**>(getVoid(id)); }

private:
    const RecRule& rule;
    uint8_t* data;
};

} // namespace cyc

#endif // CYC_RECORD_H
